[workspace]
members = ["adminapi", "matching-engine", "registry", "accountant", "registry-stub", "matching-engine-stub", "ids", "ids-stub", "accountant-stub", "traderapi", "ethereummonitor", "chainmonitor"]
resolver = "2"
