[config]
default_to_workspace = false

[tasks.add-stub-dependency-matching-engine-accountant]
args = ["add-stub-dependency", "--stub-wit-root", "matching-engine-stub/wit", "--dest-wit-root", "accountant/wit", "--overwrite", "--update-cargo-toml"]
command = "wasm-rpc-stubgen"
cwd = "."
dependencies = ["generate-matching-engine-stub"]

[tasks.add-stub-dependency-accountant-matching-engine]
args = ["add-stub-dependency", "--stub-wit-root", "accountant-stub/wit", "--dest-wit-root", "matching-engine/wit", "--overwrite", "--update-cargo-toml"]
command = "wasm-rpc-stubgen"
cwd = "."
dependencies = ["generate-matching-engine-stub"]

[tasks.add-stub-dependency-registry-accountant]
args = ["add-stub-dependency", "--stub-wit-root", "registry-stub/wit", "--dest-wit-root", "accountant/wit", "--overwrite", "--update-cargo-toml"]
command = "wasm-rpc-stubgen"
cwd = "."
dependencies = ["generate-registry-stub"]

[tasks.add-stub-dependency-ids-adminapi]
args = ["add-stub-dependency", "--stub-wit-root", "ids-stub/wit", "--dest-wit-root", "adminapi/wit", "--overwrite", "--update-cargo-toml"]
command = "wasm-rpc-stubgen"
cwd = "."
dependencies = ["generate-ids-stub"]

[tasks.add-stub-dependency-ids-traderapi]
args = ["add-stub-dependency", "--stub-wit-root", "ids-stub/wit", "--dest-wit-root", "traderapi/wit", "--overwrite", "--update-cargo-toml"]
command = "wasm-rpc-stubgen"
cwd = "."
dependencies = ["generate-ids-stub"]

[tasks.add-stub-dependency-accountant-traderapi]
args = ["add-stub-dependency", "--stub-wit-root", "accountant-stub/wit", "--dest-wit-root", "traderapi/wit", "--overwrite", "--update-cargo-toml"]
command = "wasm-rpc-stubgen"
cwd = "."
dependencies = ["generate-accountant-stub"]

[tasks.add-stub-dependency-accountant-ethereummonitor]
args = ["add-stub-dependency", "--stub-wit-root", "accountant-stub/wit", "--dest-wit-root", "ethereummonitor/wit", "--overwrite", "--update-cargo-toml"]
command = "wasm-rpc-stubgen"
cwd = "."
dependencies = ["generate-accountant-stub"]

[tasks.add-stub-dependency-matching-engine-adminapi]
args = ["add-stub-dependency", "--stub-wit-root", "matching-engine-stub/wit", "--dest-wit-root", "adminapi/wit", "--overwrite", "--update-cargo-toml"]
command = "wasm-rpc-stubgen"
cwd = "."
dependencies = ["generate-matching-engine-stub"]

[tasks.add-stub-dependency-registry-adminapi]
args = ["add-stub-dependency", "--stub-wit-root", "registry-stub/wit", "--dest-wit-root", "adminapi/wit", "--overwrite", "--update-cargo-toml"]
command = "wasm-rpc-stubgen"
cwd = "."
dependencies = ["generate-registry-stub"]

[tasks.add-stub-dependency-accountant-adminapi]
args = ["add-stub-dependency", "--stub-wit-root", "accountant-stub/wit", "--dest-wit-root", "adminapi/wit", "--overwrite", "--update-cargo-toml"]
command = "wasm-rpc-stubgen"
cwd = "."
dependencies = ["generate-accountant-stub"]

[tasks.build]
args = ["build", "--workspace", "--exclude", "chainmonitor"]
command = "cargo-component"
# This dependency removed because can't autogen stubs anymore due to circular
# dependency accountant->matching-engine->accountant
#dependencies = ["clean", "regenerate-stubs"]

[tasks.build-flow]
dependencies = ["build", "post-build"]

[tasks.build-release]
args = ["build", "--release", "--workspace", "--exclude", "chainmonitor"]
command = "cargo-component"
# This dependency removed because can't autogen stubs anymore due to circular
# dependency accountant->matching-engine->accountant
#dependencies = ["clean", "regenerate-stubs"]

[tasks.clean]
args = ["clean"]
command = "cargo-component"

[tasks.compose-accountant]
args = ["compose", "--source-wasm", "target/wasm32-wasi/debug/accountant.wasm", "--stub-wasm", "target/wasm32-wasi/debug/registry_stub.wasm", "--stub-wasm", "target/wasm32-wasi/debug/matching_engine_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/accountant_composed.wasm"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.compose-release-accountant]
args = ["compose", "--source-wasm", "target/wasm32-wasi/release/accountant.wasm", "--stub-wasm", "target/wasm32-wasi/release/registry_stub.wasm", "--stub-wasm", "target/wasm32-wasi/release/matching_engine_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/accountant_composed.wasm"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.compose-adminapi]
args = ["compose", "--source-wasm", "target/wasm32-wasi/debug/adminapi.wasm", "--stub-wasm", "target/wasm32-wasi/debug/registry_stub.wasm", "--stub-wasm", "target/wasm32-wasi/debug/ids_stub.wasm", "--stub-wasm", "target/wasm32-wasi/debug/matching_engine_stub.wasm", "--stub-wasm", "target/wasm32-wasi/debug/accountant_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/adminapi_composed.wasm"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.compose-traderapi]
args = ["compose", "--source-wasm", "target/wasm32-wasi/debug/traderapi.wasm", "--stub-wasm", "target/wasm32-wasi/debug/accountant_stub.wasm", "--stub-wasm", "target/wasm32-wasi/debug/ids_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/traderapi_composed.wasm"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.compose-matching-engine]
args = ["compose", "--source-wasm", "target/wasm32-wasi/debug/matching_engine.wasm", "--stub-wasm", "target/wasm32-wasi/debug/accountant_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/matching_engine_composed.wasm"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.compose-ethereummonitor]
args = ["compose", "--source-wasm", "target/wasm32-wasi/debug/ethereummonitor.wasm", "--stub-wasm", "target/wasm32-wasi/debug/accountant_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/ethereummonitor_composed.wasm"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.compose-release-adminapi]
args = ["compose", "--source-wasm", "target/wasm32-wasi/release/adminapi.wasm", "--stub-wasm", "target/wasm32-wasi/release/registry_stub.wasm", "--stub-wasm", "target/wasm32-wasi/release/ids_stub.wasm", "--stub-wasm", "target/wasm32-wasi/release/matching_engine_stub.wasm", "--stub-wasm", "target/wasm32-wasi/release/accountant_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/adminapi_composed.wasm"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.compose-release-traderapi]
args = ["compose", "--source-wasm", "target/wasm32-wasi/release/traderapi.wasm", "--stub-wasm", "target/wasm32-wasi/release/accountant_stub.wasm", "--stub-wasm", "target/wasm32-wasi/release/ids_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/traderapi_composed.wasm"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.compose-release-matching-engine]
args = ["compose", "--source-wasm", "target/wasm32-wasi/release/matching_engine.wasm", "--stub-wasm", "target/wasm32-wasi/release/accountant_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/matching_engine_composed.wasm"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.compose-release-ethereummonitor]
args = ["compose", "--source-wasm", "target/wasm32-wasi/release/ethereummonitor.wasm", "--stub-wasm", "target/wasm32-wasi/release/accountant_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/ethereummonitor_composed.wasm"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.default]
alias = "build"

[tasks.generate-accountant-stub]
args = ["generate", "-s", "accountant/wit", "-d", "accountant-stub"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.generate-matching-engine-stub]
args = ["generate", "-s", "matching-engine/wit", "-d", "matching-engine-stub"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.generate-registry-stub]
args = ["generate", "-s", "registry/wit", "-d", "registry-stub"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.generate-ids-stub]
args = ["generate", "-s", "ids/wit", "-d", "ids-stub"]
command = "wasm-rpc-stubgen"
cwd = "."

[tasks.post-build]
dependencies = ["compose-accountant", "compose-adminapi", "compose-traderapi", "compose-matching-engine", "compose-ethereummonitor"]

[tasks.post-build-release]
dependencies = ["compose-release-accountant", "compose-release-adminapi", "compose-release-traderapi", "compose-release-matching-engine", "compose-release-ethereummonitor"]

[tasks.regenerate-stubs]
dependencies = ["add-stub-dependency-registry-adminapi", "add-stub-dependency-ids-adminapi", "add-stub-dependency-registry-accountant", "add-stub-dependency-matching-engine-accountant", "add-stub-dependency-matching-engine-adminapi", "add-stub-dependency-accountant-adminapi", "add-stub-dependency-accountant-traderapi", "add-stub-dependency-ids-traderapi", "add-stub-dependency-accountant-matching-engine", "add-stub-dependency-accountant-ethereummonitor"]

[tasks.release-build-flow]
dependencies = ["build-release", "post-build-release"]

[tasks.test]
args = ["test"]
command = "cargo-component"
dependencies = ["clean"]
