package component: sputnik;

world registry {

  record asset-mismatch-details { incoming-asset: asset, expected-asset: asset }

  variant error {
    duplicate-id(u64),
    no-such-asset(u64),
    asset-mismatch(asset-mismatch-details),
  }

  export get-assets: func() -> list<asset>;

  export get-spot-pairs: func() -> list<spot-pair>;

  export add-asset: func(asset: asset) -> result<asset, error>;

  export add-spot-pair: func(pair: spot-pair) -> result<spot-pair, error>;

  record asset {
    id: u64,
    name: string,
    decimals: u8,
  }

  record spot-pair {
    id: u64,
    name: string,
    numerator: asset,
    denominator: asset,
  }




}