package sputnik: adminapi;

interface api {
  use sputnik: registry/api.{asset};
  use sputnik: registry/api.{hydrated-spot-pair};
  use sputnik: registry/api.{trader};
  use sputnik: ids-stub/stub-ids.{api as ids-api};

  variant error {
    unable-to-make-engine(string),
    unable-to-make-accountant(string),
    internal(string),
  }

  create-asset: func(name: string, decimals: u8, token-address: string) -> result<asset, error>;
  create-spot-pair: func(name: string, numerator: u64, denominator: u64) -> result<hydrated-spot-pair, error>;
  create-trader: func(name: string) -> result<trader, error>;
}

world adminapi {
  import sputnik: ids-stub/stub-ids;
  import sputnik: registry-stub/stub-registry;
  import sputnik: matching-engine-stub/stub-matching-engine;
  import sputnik: accountant-stub/stub-accountant;
  import sputnik: ethereummonitor-stub/stub-ethereummonitor;
  export api;
}
