package sputnik: admin-api;

interface api {
  use sputnik: ids-stub/stub-ids.{api as ids-api};
  use sputnik: registry-stub/stub-registry.{api as registry-api};

  create-asset: func() -> u64;
  create-spot-pair: func() -> u64;
}

world admin-api {
  export api;
}
