package sputnik: bitcoinmonitor;

interface api {
  variant error {
    already-initialized,
    bitcoin-error(string),
  }

  initialize: func(xpub: string, btc-asset-id: u64) -> result<_, error>;
  tick: func();
  new-address-for-trader: func(trader: u64) -> string;
}

world bitcoinmonitor {
  export api;
}