name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install protoc
        run: brew install protobuf-c
      - name: Cargo Helpers
        run: cargo install cargo-make cargo-component golem-cli
      - name: Build
        run: scripts/build.sh
      - name: Run tests
        run: cargo test --verbose
      - name: Start up docker
        run: docker-compose up -d
      - name: Integration tests
        run: scripts/integration-tests.sh

