name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: mac-os-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install protoc
        run: sudo apt-get install protobuf-compiler
      - name: Build
        run: scripts/build.sh
      - name: Run tests
        run: cargo test --verbose
